server:
  port: 8084

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://postgres-order-dev:5432/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration/dev
    baseline-on-migrate: true
    validate-on-migrate: true

product:
  service:
    url: http://product-service-dev:8082

user:
  service:
    url: http://user-service-dev:8081
